package com.github.kmu_wink.wink_official_page.domain.recruit.constant

enum class BackendTechStack : TechStack {
    JAVASCRIPT,
    TYPESCRIPT,
    JAVA,
    PYTHON,
    EXPRESS,
    NESTJS,
    SPRING_BOOT,
    DJANGO,
    FLASK,
    FASTAPI,
    MYSQL,
    MARIADB,
    POSTGRESQL,
    MONGODB,
    REDIS,
    ELASTICSEARCH,
    TYPEORM,
    PRISMA,
    SEQUELIZE,
    JPA,
    HIBERNATE,
    GRAPHQL,
    REST,
    GRPC,
    WEBSOCKET,
    KAFKA,
    RABBITMQ,
    JWT,
    OAUTH,
    JUNIT,
    JEST,
}
