package com.github.kmu_wink.wink_official_page.domain.recruit.constant

enum class FrontendTechStack : TechStack {
    HTML,
    CSS,
    JAVASCRIPT,
    TYPESCRIPT,
    SCSS,
    SASS,
    TAILWIND_CSS,
    BOOTSTRAP,
    MATERIAL_UI,
    STYLED_COMPONENT,
    EMOTION,
    REACT,
    VUE,
    ANGULAR,
    SVELTE,
    NEXT_JS,
    NUXT_JS,
    JQUERY,
    REDUX,
    MOBX,
    RECOIL,
    ZUSTAND,
    CONTEXT_API,
    JOTAI,
    JEST,
    TESTING_LIBRARY,
    CYPRESS,
    STORYBOOK,
    GRAPHQL,
    REACT_QUERY,
    APOLLO_CLIENT,
    SWR,
}
